### ISSUE TITLE
Pub releases?

### ISSUE THREAD

**Issue by johnpryan** [PointyCastle/pointycastle#109]
to use the latest version requires using github as a source in `pubspec.yaml` rather than `pub.dartlang.org`

Could we tag a new release of `master`?

**Comment by stevenroose** [comment]
You can just use the pub release.. Are there source commits that are not yet released?

**Comment by stevenroose** [comment]
I just bumped the version to push the reflectable update, I'm sorry I forgot that. You should be able to pub upgrade.

**Comment by johnpryan** [comment]
thanks!
