### ISSUE TITLE
Copy cipher's wiki to pointycastle

### ISSUE THREAD

**Issue by modulovalue** [PointyCastle/pointycastle#136]
Cipher has a wiki [here](https://github.com/izaera/cipher/wiki/) and a great overview of (almost all) provided algorithms [here](https://github.com/izaera/cipher/wiki/Table-of-provided-algorithms/).

I think it would be great to at least copy the wiki from cipher to pointycastle.
This also might be the first step that could spark more participation from the community towards improving the documentation

**Comment by leocavalcante** [comment]
It could be Markdown files in a docs directory so people can contribute with mirroring.

**Comment by AKushWarrior** [comment]
A lot of these aren't relevant anymore, or are wholly dysfunctional.
