### ISSUE TITLE
Can I use OAEP RSA in flutter?

### ISSUE THREAD

**Issue by lionlin** [PointyCastle/pointycastle#156]

**Comment by duncanhoggan** [comment]
@lionlin I'm busy working on it will update this thread accordingly.

**Comment by lionlin** [comment]
thanks for reply. when will it be ready for rsa-oaep?

**Comment by AquaWolf** [comment]
Hi, any news about this issue?

**Comment by duncanhoggan** [comment]
@lionlin and @AquaWolf I went in and checked the re-write again and looks like its good, written against the BC Java OAEP encoding [here](https://github.com/bcgit/bc-java/blob/5d17720a0d5d61f2b6b198a059caccbda811724f/core/src/main/java/org/bouncycastle/crypto/encodings/OAEPEncoding.java).

I'll push the changes and link them here, will just need to updated the project tests before the PR comes in.

**Comment by duncanhoggan** [comment]
@lionlin and @AquaWolf [PR](https://github.com/PointyCastle/pointycastle/pull/160) is in.

**Comment by stevenroose** [comment]
@lionlin @AquaWolf I would very much appreciate if either of you could verify if @duncanhoggan's implementation works for you :)
https://github.com/PointyCastle/pointycastle/pull/160

I'd feel more confident pulling it that way.

**Comment by stevenroose** [comment]
Fixed per https://github.com/PointyCastle/pointycastle/pull/160.
Available in v1.0.0
