### ISSUE TITLE
Update pointycastle in pub repository

### ISSUE THREAD

**Issue by SoptikHa2** [PointyCastle/pointycastle#161]
The package last version in pub repository is outdated, is it possible to update it to latest version? Importing package with pub is much easier, as I don't need to manage the versions and dependencies myself.

**Comment by stevenroose** [comment]
The only change since the last pub version (1.0.0-rc4) is formatting.

If I get some confirmations that rc4 works decently with Dart2, I could
release 1.0.0 stable.

**Comment by SoptikHa2** [comment]
Thanks. I didn't see the new version, directly searching for pointycastle brought me to old 0.11.1 version and I missed the link to new version.
