### ISSUE TITLE
ChaCha20 support

### ISSUE THREAD

**Issue by yunge** [PointyCastle/pointycastle#182]
Is there any plan to add ChaCha20? Thanks.

**Comment by gi097** [comment]
You could temporarliy use this, since I needed chacha20 in Dart as well: https://github.com/gi097/salt

**Comment by stevenroose** [comment]
No plans to add anything. I'm not even maintaining really anymore except when someone finds a real bug.

You're very much encouraged to provide an implementation of ChaCha20 for PointyCastle. I'd happily spend the time reviewing it.

**Comment by yunge** [comment]
> You could temporarliy use this, since I needed chacha20 in Dart as well: https://github.com/gi097/salt

Thanks, I'll try it.
