### ISSUE TITLE
Support for AES-256-GCM encryption/decryption

### ISSUE THREAD

**Issue by ravitejaavv** [PointyCastle/pointycastle#237]
Hi, I want to know if it is (or if it will be) possible to encrypt/decrypt using AES and the Galois/Counter Mode (GCM) with your library.

Thanks by advance

**Comment by izaera** [comment]
See this please -> https://github.com/PointyCastle/pointycastle/blob/master/README.md

**Comment by izaera** [comment]
this project has moved.
