### ISSUE TITLE
When the input is long enough, SHA384 often returns wrong result. for short input like 10 20 bytes, it seems to be fine

### ISSUE THREAD

**Issue by stevenroose** [PointyCastle/pointycastle#92]
_From @izaera on January 22, 2015 7:59_

Hi

in the dart cipher pub package
I found when the input is long enough, SHA384 often returns wrong result. for short input like 10 20 bytes, it seems to be fine.

btw, I'm testing in dartvm,

a test case:

SHA384Digest sha = new SHA384Digest();
print(sha.process(UTF8.encode('1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012')));

// output: [162, 16, 86, 170, 176, 212, 206, 236, 153, 72, 18, 214, 163, 232, 46, 58, 183, 219, 82, 127, 35, 105, 243, 234, 247, 111, 177, 42, 221, 159, 71, 14, 57, 121, 57, 192, 150, 98, 90, 70, 103, 148, 165, 98, 120, 84, 148, 243]
// and this is different from the result I get from any other framework:  8f3cbbf964af56b83b52f7182cd171fab20810103603d4213217914145388dca1cad5fe88dcdbc56cf3ff5fc7fb82ae8

_Copied from original issue: izaera/cipher#92_

**Comment by TheBosZ** [comment]
:+1:  Trying to write a server that uses a legacy PHP database with SHA-512 hashed passwords. The string returned using this library doesn't match the PHP string.

**Comment by stevenroose** [comment]
Can you provide an example String that returns an incorrect hash that I can
test against?

**Comment by stevenroose** [comment]
And BTW, there is a SHA-512 implementation, this issue is about SHA-384.

**Comment by TheBosZ** [comment]
I realize that this is about SHA-384, but SHA-512 has the same problem so I thought it was related.

Here's a PHP example: http://codepad.org/iwRVbvQT
Hash: 
`907c90d3c7e9f783dc9427f510c0e6b4f11a0caf85b7d86c53bf5612a77ca8e0691def03232dbfcf95ad2bb45f4752355442b6d6a469722f37a8e166b5364702`

The Dart version: https://gist.github.com/anonymous/8fab686d1edbb07df6ed
Hash: 
`261ee5b5cb3667ab6a278da2c1064a8b6fdb67380a1d5511aa7400899fecb2a4a6e5546ed3a3f43144d8c3e77ecaf671915ef60f9c5d798ccbbf449fc9841aa0`

**Comment by TheBosZ** [comment]
Shorter strings match (`The quick brown fox jumped over the lazy dog.` matches for both).

**Comment by stevenroose** [comment]
Ok, I will take a look at it when I get back from vacation, around the 10th
of March.

Btw, you do realise that `codeUnitAt` encodes as UTF-16? I don't know how
the PHP method encodes, but you can do UTF-8 encoding in Dart using
`UTF8Codec` from the `dart:convert` library.

**Comment by TheBosZ** [comment]
Because the documentation doesn't talk about what the digest methods expect, I just copied and pasted from the test scripts.

What should I change?

**Comment by stevenroose** [comment]
Try something like this:
https://gist.github.com/stevenroose/d6dc6f35252d7f880ac7

**Comment by TheBosZ** [comment]
It returns the same result as before:
`261ee5b5cb3667ab6a278da2c1064a8b6fdb67380a1d5511aa7400899fecb2a4a6e5546ed3a3f43144d8c3e77ecaf671915ef60f9c5d798ccbbf449fc9841aa0`
Using:
https://gist.github.com/TheBosZ/857aa27a07945b20c7fa

**Comment by izaera** [comment]
These digests work block by block, so this is probably a problem when more than 1 block is processed. Maybe you can check if that is the case...

Also, don't rely on encodings when testings algorithms, resort to raw bytes and that way you can forget about whether encoding is done right/bad. Once you know the digest algorithm works, you may debug the encoding thing.

**Comment by stevenroose** [comment]
I've gone over the implementation of `LongSHA2FamilyDigest` and BC's `LongDigest` several times and apart from a few things that I don't fully understand (but that are used also for shorter digests), I cannot find anything looking differently.

(If you don't want to checkout BC, it's here: https://github.com/bcgit/bc-java/blob/master/core/src/main/java/org/bouncycastle/crypto/digests/LongDigest.java)
(The Dart counterpart is in `lib/src/impl/long_sha2_familiy_digest.dart`.)

**Comment by TheBosZ** [comment]
Can we test what BC does with the long digests? Does it return the correct hash?

If not, it could be a bug in that implementation that came over with this re-implementation.

**Comment by stevenroose** [comment]
Yes it does it right. That's why I was looking at this, there probably is an error in the re-implementation. OF course with the more eyes on it... I cannot seem to find something, I looked it up and down line by line twice.

**Comment by TheBosZ** [comment]
If I have any spare time today, I'll take a look and see if I can find anything.

**Comment by stevenroose** [comment]
The two parts that I could not verify completely (because they are quite complex.. I might try now) are in `_processBlock()`, the stuff in the for-loop at the start and the large for-loop lateron. But since `_processBlock()` is called also for small input sized, I doubt how it can be the culprit.

**Comment by TheBosZ** [comment]
I agree that the logic is quite complex. I'm trying to pull it apart to simplify it down some.

**Comment by TheBosZ** [comment]
My simplified version passes the test.

I'm going to run the full suite of tests before I submit a PR.

**Comment by TheBosZ** [comment]
I can confirm that my PR fixes the issues I was seeing in working with my PHP-based hashes.

**Comment by stevenroose** [comment]
Aha, nice! I looked at your PR and the actual bug was in the first for loop, instead of performing this formula

```
_W[t] = _Sigma1(_W[t - 2]) + _W[t - 7] + _Sigma0(_W[t - 15]) + _W[t - 16];
```

it did this 

```
_W[t] += _Sigma1(_W[t - 2]) + _W[t - 7] + _Sigma0(_W[t - 15]) + _W[t - 16];
```

Wow!

**Comment by TheBosZ** [comment]
Right, I see it now!

I had to simplify it so I could make sure the logic matched and inadvertently uncovered the problem.

Feel free to reject my PR in favor of just fixing that bit.

**Comment by stevenroose** [comment]
I merged it, but just reverted it back to using sum. Awesome find, thanks!

Closed by 22665686fe62b7dd086287982d6cf63dfc198678

**Comment by TheBosZ** [comment]
:+1:

**Comment by izaera** [comment]
Just for the record. I used to debug implementations by running a copy of the algorithm in Java and the same in Dart, side by side. Then I placed random checkpoints in the code, in both copies, and dumped the internal state of the algorithm. By moving the checkpoints I narrowed the offending code. It was easy to catch bugs like that and didn’t involve too much thinking, just comparison.

Cheers,
Ivan
