### ISSUE TITLE
The link to the GitHub repo is broken

### ISSUE THREAD

**Issue by zoechi** [PointyCastle/pointycastle#97]
(Homepage) https://pub.dartlang.org/packages/pointycastle

**Comment by sethladd** [comment]
Noticed that, too. :)

Homepage in pubspec.yaml points to pointycastle.github.io but that's a 404. Can we point to the main github repo for now?

**Comment by sethladd** [comment]
Addressed by https://github.com/PointyCastle/pointycastle/pull/98
